## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'ftir'  

package-url = 'https://github.com/CEMES-CNRS/pymodaq_plugins_ftir' 
description = 'Fourier transform infrared spectrometer at CEMES'

author = 'Sebastien Weber'
author-email = 'sebastien.weber@cemes.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pymodaq_plugins_daqmx', 'pymodaq_plugins_smaract']
